-- Migration: Insert default templates (revised)
INSERT INTO templates (id, title, category, intent, content, why_it_works) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Concise Summary', 'summary', 'brief',
 'Summarize the following text for a business audience in 4 bullet points, plus 1 bullet for any key risk. Include any dates or locations mentioned, or ''unknown'' if none. Limit each bullet to 20 words or less.\n\nText:\n{{insert text}}',
 'Emphasizes audience, format, and handling of missing info; ensures concise output.'),
('550e8400-e29b-41d4-a716-446655440002', 'Executive Summary', 'summary', 'brief',
 'Write a concise executive summary for C-level executives based on the report below. Include: 1) main finding (one sentence), 2) three key metrics (with context), 3) one critical risk or opportunity, 4) one recommended action. Keep it under 150 words.\n\nReport:\n{{insert report}}',
 'Focuses on key insights and actions for executives with a word limit for brevity.'),
('550e8400-e29b-41d4-a716-446655440003', 'Decision Rationale', 'analysis', 'insight',
 'Explain why the decision on {{topic}} was made, for {{audience}}. Include: 1) three key factors, 2) two trade-offs, 3) one counterpoint, 4) missing data. Present answers as bullet points.',
 'Guides reasoning with key factors, trade-offs, and data gaps; clarifies decision logic.'),
('550e8400-e29b-41d4-a716-446655440004', 'Root Cause Diagnosis', 'analysis', 'diagnosis',
 'Analyze the following problem to identify root causes. For each cause, include: 1) the cause, 2) evidence from the text, 3) confidence (high/medium/low), 4) one preventive measure. If evidence is lacking, note what data is needed.\n\nProblem:\n{{insert problem description}}',
 'Promotes evidence-based analysis and highlights missing data, reducing speculation.'),
('550e8400-e29b-41d4-a716-446655440005', 'Compare Options', 'compare', 'evaluation',
 'Compare {{option A}} vs {{option B}} for {{audience}}. List each relevant criterion and why it matters. For each criterion, note how {{option A}} and {{option B}} perform. End with a brief recommendation and one risk.',
 'Encourages structured side-by-side comparison and a clear recommendation.'),
('550e8400-e29b-41d4-a716-446655440006', 'Feature Comparison', 'compare', 'evaluation',
 'Compare {{option A}}, {{option B}}, and {{option C}} for {{use case}}. List features relevant to this use case, and for each feature note how each option performs. Indicate which option is best per feature. End with a recommendation based on {{priority}} (cost, performance, ease-of-use).\n\nUse case: {{insert use case}}\nPriority: {{insert priority}}',
 'Structures multi-option comparison with prioritized criteria to simplify decisions.'),
('550e8400-e29b-41d4-a716-446655440007', 'Structured Extraction', 'extract', 'extract',
 'Extract the required fields from the text. Return JSON with keys: title, date, audience, and actions. Use null for any missing value, and list missing field names in an "unknowns" array.\n\nText:\n{{insert text}}',
 'Defines a clear output schema and handles missing data explicitly to avoid errors.'),
('550e8400-e29b-41d4-a716-446655440008', 'Contact Info Extraction', 'extract', 'extract',
 'Extract contact information (name, email, phone, company) from the text. Output JSON with keys "name", "email", "phone", "company" (strings or null) and "validation": {"emailValid": boolean, "phoneValid": boolean}. Use null if missing and set validation flags false for invalid formats.\n\nText:\n{{insert text}}',
 'Standardizes contact info output with validation flags to improve data accuracy.'),
('550e8400-e29b-41d4-a716-446655440009', 'Critique and Improve', 'critique', 'review',
 'Critique the draft below for clarity, completeness, and tone for {{audience}}. Provide: 1) Three issues, 2) Three suggestions for improvement, 3) one example rewrite (<= 120 words). If important context is missing, list those items first.\n\nDraft:\n{{insert draft}}',
 'Separates critique from solutions, highlighting issues and fixes while keeping the rewrite concise.'),
('550e8400-e29b-41d4-a716-446655440010', 'Code Review', 'critique', 'review',
 'Review the following {{language}} code for best practices. Provide: 1) Three issues with line references, 2) why each is a problem, 3) an example fix (5-10 lines) for the most critical issue. Focus on readability, maintainability, and potential bugs.\n\nCode:\n{{insert code}}',
 'Structures feedback with examples and clear issues, improving code quality and clarity.'),
('550e8400-e29b-41d4-a716-446655440011', 'Content Plan', 'writing', 'content',
 'Create a plan for the {{piece type}} intended for {{audience}}. Include: 1) the goal, 2) key questions the reader has, 3) an outline (bullet points), 4) voice/tone guidelines, 5) sources for facts. Keep under 160 words.',
 'Enforces upfront planning with clear goals and sources to reduce later revisions.'),
('550e8400-e29b-41d4-a716-446655440012', 'Email Draft', 'writing', 'content',
 'Draft a {{tone}} email to {{recipient}} about {{topic}}. Include: 1) a clear subject line, 2) a 1-2 sentence opening, 3) the main message (2-3 bullet points), 4) a call to action, 5) a professional closing. Keep it under 150 words.',
 'Provides a clear email structure to improve clarity and response rates.'),
('550e8400-e29b-41d4-a716-446655440013', 'Blog Post Outline', 'writing', 'content',
 'Outline a blog post titled "{{title}}" for {{audience}}. Include: 1) a hook idea, 2) three main sections (2-3 bullet points each), 3) a conclusion idea, 4) a call-to-action. Keep the outline under 200 words.',
 'Builds structure before writing to ensure a logical flow and complete content.'),
('550e8400-e29b-41d4-a716-446655440014', 'Technical Documentation', 'writing', 'content',
 'Write technical documentation for {{feature}} for {{audience}} (beginner, intermediate, or advanced). Include: 1) an overview of what it does, 2) prerequisites, 3) step-by-step instructions (with code examples if needed), 4) common issues and solutions. Use clear headings and code blocks.',
 'Organizes documentation clearly with practical details and examples for usability.'),
('550e8400-e29b-41d4-a716-446655440015', 'Key Takeaways', 'summary', 'brief',
 'Summarize the main points of the following text in bullet points for a general audience. Provide 5 key takeaways. Note ''unknown'' if information is missing.\n\nText:\n{{insert text}}',
 'Focuses on distilling essential information clearly, highlighting missing data.'),
('550e8400-e29b-41d4-a716-446655440016', 'Meeting Summary', 'summary', 'brief',
 'Summarize the following meeting notes into key bullet points for stakeholders. Include decisions made, action items, and any open questions. Keep it under 150 words.\n\nNotes:\n{{insert notes}}',
 'Provides a concise overview of meeting outcomes and follow-up items.'),
('550e8400-e29b-41d4-a716-446655440017', 'SWOT Analysis', 'analysis', 'analysis',
 'Perform a SWOT analysis for {{topic}}. List 3 bullet points under each heading: Strengths, Weaknesses, Opportunities, Threats.',
 'Structures a strategic analysis into clear categories of strengths, weaknesses, etc.'),
('550e8400-e29b-41d4-a716-446655440018', 'Cost-Benefit Analysis', 'analysis', 'analysis',
 'Perform a cost-benefit analysis for {{project}}. Provide at least three bullet points for costs and three for benefits, with brief explanations. End with a recommendation.',
 'Highlights major costs and benefits to inform decision-making with a clear recommendation.'),
('550e8400-e29b-41d4-a716-446655440019', 'Pros and Cons Comparison', 'compare', 'evaluation',
 'Compare {{option A}} and {{option B}}. For each option, list 3 pros and 3 cons. Provide a brief recommendation at the end.',
 'Simplifies comparison into advantages/disadvantages for quick evaluation.'),
('550e8400-e29b-41d4-a716-446655440020', 'Decision Matrix', 'compare', 'evaluation',
 'Compare {{option A}}, {{option B}}, and {{option C}} by scoring them on several criteria (e.g., cost, quality, risk). For each criterion, assign a score to each option. Present this in a clear table or list. Conclude by naming the best option and why.',
 'Provides a clear, quantitative basis for choosing between multiple options.'),
('550e8400-e29b-41d4-a716-446655440021', 'Named Entity Extraction', 'extract', 'extract',
 'Extract named entities from the text below. Return JSON: {"people": [...], "organizations": [...], "locations": [...]}. List each entity as a string. Use empty array if none found.\n\nText:\n{{insert text}}',
 'Structures extraction of key entities into JSON arrays for further analysis.'),
('550e8400-e29b-41d4-a716-446655440022', 'Timeline Extraction', 'extract', 'extract',
 'Extract all events with dates from the text. Return a JSON array of objects with keys "event" and "date" (YYYY-MM-DD). If an event has no date, use null for the date.\n\nText:\n{{insert text}}',
 'Organizes chronological information clearly, handling missing dates explicitly.'),
('550e8400-e29b-41d4-a716-446655440023', 'Peer Feedback', 'critique', 'review',
 'Review the draft below for {{audience}}. Provide: 1) Two strengths, 2) Two weaknesses, 3) one improved example (<= 50 words). Focus on clarity.\n\nDraft:\n{{insert draft}}',
 'Encourages constructive feedback by highlighting positives, issues, and an actionable rewrite.'),
('550e8400-e29b-41d4-a716-446655440024', 'Design Review', 'critique', 'review',
 'Evaluate the following design proposal. List two strong points and two concerns, and suggest one improvement. Focus on functionality and user experience.\n\nDesign:\n{{insert description}}',
 'Organizes design critique into clear positives, issues, and one actionable improvement.'),
('550e8400-e29b-41d4-a716-446655440025', 'Social Media Post', 'writing', 'content',
 'Draft a social media post about {{topic}}. Use a friendly, engaging tone. Include a catchy opening, one or two main points, and a call to action. Keep it under 280 characters.',
 'Focuses the message for brevity and engagement on social platforms.'),
('550e8400-e29b-41d4-a716-446655440026', 'Press Release', 'writing', 'content',
 'Draft a press release for {{announcement}}. Include: 1) headline, 2) one-sentence lead, 3) two short paragraphs of details, 4) company boilerplate. Use a professional tone.',
 'Ensures standard press release format with clear structure and content.'),
('550e8400-e29b-41d4-a716-446655440027', 'Proposal Outline', 'writing', 'content',
 'Create an outline for a project proposal titled "{{title}}". Include: 1) objective, 2) approach or methodology, 3) timeline, 4) budget. Use bullet points.',
 'Organizes key elements of a proposal clearly before writing the full document.'),
('550e8400-e29b-41d4-a716-446655440028', 'Meeting Agenda', 'writing', 'content',
 'Draft an agenda for a meeting on {{topic}}. Include: 1) title, 2) meeting objective, 3) list of agenda items with time slots, 4) expected outcomes. Keep it concise.',
 'Provides clear structure to guide a productive meeting.')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  intent = EXCLUDED.intent,
  content = EXCLUDED.content,
  why_it_works = EXCLUDED.why_it_works;
